### ISSUE TITLE
TypeError: argument 'mode': 'int' object cannot be converted to 'ImgColor'

### ISSUE THREAD

**Issue by Uranite** [umzi2/Dataset_Preprocessing#1]
I'm on windows, using python 3.12.4
i also tried using venv by running
```pwsh
py -m venv venv
.\venv\Scripts\Activate.ps1
pip install -r .\requirements.txt
```
Here is the full traceback
https://pastes.dev/ebezdKsTm3
Something that might be of interest, the version of the dependencies installed seems to be newer than the one on requirements.txt
`Successfully installed chainner-ext-0.3.10 colorama-0.4.6 numpy-1.26.4 opencv-python-4.9.0.80 pepeline-0.3.8 tqdm-4.66.4`

**Comment by umzi2** [comment]
I apologise for the oversight regarding this project. Lately, under the influence of a friend's persuasion, I have modified the reading API within the pepeline, which has resulted in minor issues across all my projects. You may either revert to using the 3.7 pepeline or allow me some time to rectify the situation.

**Comment by umzi2** [comment]
fixed it
